apiVersion: v1
kind: Service
metadata:
  name: {{ template "api.serviceName" . }}
spec:
  selector:
    app: {{ template "api.labelName" . }}
  ports:
  - port: 80
    targetPort: 80
  type: {{ .Values.api.serviceType }}