apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "api.deploymentName" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "api.labelName" . }}
  template: 
    metadata:          
      labels:
        app: {{ template "api.labelName" . }}
    spec:            
      containers:
      - name: api
        image: {{ .Values.api.image }}:{{ .Values.api.tag }}
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        resources: {}
        env:
          - name: Mongo__User
            valueFrom:
              secretKeyRef:
                key: MONGO_INITDB_ROOT_USERNAME
                {{- if empty .Values.mongodb.existSecret }}
                name: {{ template "mongodb.secretName" . }}
                {{- else }}
                name: {{ .Values.mongodb.existSecret }}
                {{- end }}
          - name: Mongo__Password
            valueFrom:
              secretKeyRef:
                key: MONGO_INITDB_ROOT_PASSWORD
                {{- if empty .Values.mongodb.existSecret }}
                name: {{ template "mongodb.secretName" . }}
                {{- else }}
                name: {{ .Values.mongodb.existSecret }}
                {{- end }}
        envFrom:
          - configMapRef:
              name: {{ template "api.configmapName" . }}
