apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "mongodb.deploymentName" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "mongodb.labelName" . }}
  template:
    metadata:     
      labels:
        app: {{ template "mongodb.labelName" . }}
    spec:
      containers:
      - name: mongodb
        image: {{ .Values.mongodb.image }}:{{ .Values.mongodb.tag }}
        ports:
        - containerPort: 27017
        resources: {}
        envFrom:
          - secretRef:
              {{- if empty .Values.mongodb.existSecret }}
              name: {{ template "mongodb.secretName" . }}
              {{- else }}
              name: {{ .Values.mongodb.existSecret }}
              {{- end }}
